nodeLinker: pnp

pnpEnableInlining: false

pnpMode: loose

enableGlobalCache: false

packageExtensions:
  "@prisma/client@*":
    dependencies:
      prisma: "*"
  
  # Node builtins for @types packages
  "undici-types@*":
    dependencies:
      "@types/node": "*"
  
  "@types/node@*":
    dependencies:
      buffer: "*"
      events: "*"
      string_decoder: "*"
  
  "@types/pg@*":
    dependencies:
      events: "*"
      "@types/node": "*"
  
  "bull@*":
    dependencies:
      events: "*"
  
  "ioredis@*":
    dependencies:
      events: "*"
  
  "engine.io@*":
    dependencies:
      events: "*"
  
  "socket.io@*":
    dependencies:
      events: "*"
  
  "socket.io-adapter@*":
    dependencies:
      events: "*"
  
  # @types missing dependencies
  "@types/jsonwebtoken@*":
    dependencies:
      ms: "*"
  
  "@types/express@*":
    dependencies:
      serve-static: "*"
      body-parser: "*"
  
  "@types/express-serve-static-core@*":
    dependencies:
      send: "*"
      events: "*"
      qs: "*"
      range-parser: "*"
  
  "@types/serve-static@*":
    dependencies:
      http-errors: "*"
  
  "@types/passport@*":
    dependencies:
      express: "*"
  
  "@types/passport-jwt@*":
    dependencies:
      jsonwebtoken: "*"
      passport-strategy: "*"
  
  "@types/passport-strategy@*":
    dependencies:
      express: "*"
  
  "@types/passport-local@*":
    dependencies:
      passport-strategy: "*"
      express: "*"
  
  "@types/cookie-parser@*":
    dependencies:
      express: "*"
  
  "@types/nodemailer@*":
    dependencies:
      events: "*"
  
  "@types/supertest@*":
    dependencies:
      superagent: "*"
      methods: "*"
  
  "@types/superagent@*":
    dependencies:
      methods: "*"
      buffer: "*"
      cookiejar: "*"

supportedArchitectures:
  os:
    - current
  cpu:
    - current